default-task = 'build'
version = 0.1

extensions = ['chomp@0.1:swc', 'chomp@0.1:jspm', 'chomp@0.1:npm']

[template-options.npm]
auto-install = true

[[task]]
deps = ['copy', 'lib/static-resources.json', 'lib/**/*.html', 'deno.importmap']
name = 'build'

[[task]]
deps = ['browser', 'lib/**/*.html', 'deno.importmap', 'server.tsx', 'lib/static-resources.json']
name = 'serve'
run = 'deno run -A --import-map=deno.importmap --unstable --no-check server.tsx'

[[task]]
name = 'browser'
deps = ['jsx', 'ts']

[[task]]
name = 'ts'
dep = 'src/#.ts'
target = 'lib/#.js'
template = 'swc'

[[task]]
name = 'jsx'
dep = 'src/#.tsx'
target = 'lib/#.js'
template = 'swc'
[task.template-options.config]
'jsc.parser.tsx' = true
'jsc.transform.react.pragma' = 'h'

[[task]]
name = 'clean'
run = 'rm deno.importmap ; rm lib/* ;'
validation = 'none'

[[task]]
name = 'copy'
dep = 'src/#.js'
run = 'cp $DEP $TARGET'
target = 'lib/#.js'

# [[task]]
# deps = ['server.tsx', 'lib/static-resources.json']
# target = 'deno.importmap'
# template = 'jspm'
# [task.template-options]
# env = ['deno', 'production']
# [task.template-options."inputMap".imports]
# nano-jsx = 'https://deno.land/x/nano_jsx@v0.0.33/mod.ts'

[[task]]
targets = ['deno.importmap']
deps = [
    'server.tsx',
    'lib/static-resources.json',
    'npm:install',
]
invalidation = 'always'
engine = 'node'
run = '''
    import { Generator } from '@jspm/generator';
    import { readFile, writeFile } from 'fs/promises';
    import { pathToFileURL } from 'url';
    import mkdirp from 'mkdirp';
    import { dirname } from 'path';

    const generator = new Generator({
      mapUrl: import.meta.url,
      env: ["deno", "production"], 
      defaultProvider: 'jspm.cachefly',
      inputMap: {
        imports: {
          "nano-jsx": "https://deno.land/x/nano_jsx@v0.0.33/mod.ts"
        }
      }
    });

    await Promise.all(process.env.DEPS.split(':').map(dep => generator.traceInstall('./' + dep)));

    mkdirp.sync(dirname(process.env.TARGET));
    await writeFile(process.env.TARGET, JSON.stringify(generator.getMap(), null, 2));
'''

[[task]]
deps = ['src/#.html', 'browser', 'npm:install']
engine = 'node'
invalidation = 'always'
run = '''
    import { Generator } from '@jspm/generator';
    import { readFile, writeFile } from 'fs/promises';
    import { pathToFileURL } from 'url';
    import mkdirp from 'mkdirp';
    import { dirname } from 'path';

    const generator = new Generator({
      mapUrl: pathToFileURL(process.env.TARGET),
      env: ["browser", "production"], 
      defaultProvider: 'jspm.cachefly'
    });

    const htmlSource = await readFile(process.env.DEP, 'utf-8');

    mkdirp.sync(dirname(process.env.TARGET));
    await writeFile(process.env.TARGET, await generator.htmlInject(htmlSource, {
      // custom task required to set this up for now!
      htmlUrl: pathToFileURL('process.env.TARGET'),
      preload: true,
      integrity: true, // erring ATM
      whitespace: true,
      esModuleShims: true,
      comment: true,
      trace: true
    }));
'''
target = 'lib/#.html'

[[task]]
deps = ['lib/**/*.html', 'browser', 'npm:install']
engine = 'node'
invalidation = 'always'
run = '''
   import './generate-static-resources-map.js';
'''
target = 'lib/static-resources.json'

[[task]]
deps = ['package.json', 'npm:install']
engine = 'node'
invalidation = 'always'
name = 'exportmap'
run = '''
   import './generate-exportmap.js';
'''
