name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Setup Chomp
      uses: guybedford/chomp-action@v1
    - name: Build with Chomp
      run: chomp build
    - name: Upload to Deno Deploy
      uses: denoland/deployctl@v1
      with:
        project: "jspm-packages"
        import-map: "file:///deno.importmap"
        entrypoint: "file:///server.jsx"
