name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-ubuntu:
    name: Build with Chomp
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Chomp
      uses: guybedford/chomp-action@v1
    - name: Generate importmap for Deno
      run: chomp deno.importmap